config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'tweets#index'

  resources :tweets, only: :index

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweets = TwitterSearcher.search(term: params[:search])

    expires_in 5.minutes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def tweet_content(content)
    content.gsub(/@(\w+)/, "<a target='_blank' href='http://twitter.com/\\1'>@\\1</a>").html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterapi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <% if current_user %>
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'TwitterConsumer', root_path, class: 'navbar-brand' %>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <%= form_tag tweets_path, class: 'navbar-form navbar-left', role: 'search', :method => 'get' do %>
              <div class="form-group">
                <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search' %>
                <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
              </div>
            <% end %>

            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>

    <div class="container">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/tweets/index.html.erb
<div class="row">
  <div class="col-md-12 centered">
    <% @tweets.each do |tweet| %>
      <blockquote class="twitter-tweet">
        <p><%=tweet_content(tweet.text) %></p>
         <footer><%= link_to tweet.user.try(:name), "http://twitter.com/#{tweet.user.try(:screen_name)}", target: "_blank" %> / <cite><%=l tweet.created_at, format: :short %></cite></footer>
      </blockquote>
    <% end %>
  </div>
</div>